### ISSUE TITLE
dials-full pipeline dropping files in unexpected places

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#246]
```
26_ctruncate.log
27_freerflag.log
28_freerflag.log
26_truncate.xml
```
```
XTAL/
XTAL/report
XTAL/report/xtriage.log
XTAL/report/29_xia2.plot_multiplicity.log
XTAL/report/29_multiplicities_h_0.png
XTAL/report/29_multiplicities_h_0.json
XTAL/report/30_xia2.plot_multiplicity.log
XTAL/report/30_multiplicities_k_0.png
XTAL/report/30_multiplicities_k_0.json
XTAL/report/31_xia2.plot_multiplicity.log
XTAL/report/31_multiplicities_l_0.png
XTAL/report/31_multiplicities_l_0.json
```

should go into ```./$DEFAULT/scale/``` and ```./$DEFAULT/report/``` respectively

**Comment by graeme-winter** [comment]
@jbeilstenedmands probably easiest if you wanted to take a look at this? @Anthchirp good spot 🙂

**Comment by jbeilstenedmands** [comment]
Yes i'll have a look at this now

**Comment by jbeilstenedmands** [comment]
I've addressed the first lot of files but having trouble with the second.

I think it's generated by this line: https://github.com/xia2/xia2/blob/f9dc9c3788214219358ba7fbf93d0c2b3353e1e0/command_line/report.py#L84
i.e. base_dir is not set, but it looks like this is maybe due to this line:
https://github.com/xia2/xia2/blob/f9dc9c3788214219358ba7fbf93d0c2b3353e1e0/command_line/html.py#L71

However I don't think I've touched these, so i'm not sure why it's different compared to the other pipeline

**Comment by graeme-winter** [comment]
Yay for emergent behaviour! 

```
          hklout = os.path.join(self.get_working_directory(),
                                '%s_%s_%s_%s_prepointless.mtz' % \
                                (pname, xname, dname, si.get_sweep_name()))
```

in aimless

```
  mtz_crystal = mtz_file.add_crystal('XTAL', 'DIALS', unit_cell.parameters())
  mtz_dataset = mtz_crystal.add_dataset('FROMDIALS', experiment_list[0].beam.get_wavelength())
```

in dials.export => overrides names which xia2 report uses => need to be able to set pname / xname / dname in dials.export to fix this
