### ISSUE TITLE
Need unit cell errors in output

### ISSUE THREAD

**Issue by Anthchirp** [xia2/xia2#4]
self-explanatory

**Comment by graeme-winter** [comment]
This may be useful for e.g. processing with BLEND as well as regular linear processing.

Can easily run a cycle of static refinement at the end to get final static unit cell etc. @dagewa @rjgildea we should perhaps try running refinement with integrated.pickle?!

**Comment by graeme-winter** [comment]
FWIW refinement with integrated.pickle seems to work (!) though not sure if the results are correct....

```
Refined cell parameters and estimated standard deviations:
a: 67.634976 +/- (0.001988) Angstroms
b: 78.978647 +/- (0.002388) Angstroms
c: 78.048452 +/- (0.002476) Angstroms
alpha: 90.000000 +/- (0.000000) degrees
beta:  90.984866 +/- (0.000717) degrees
gamma: 90.000000 +/- (0.000000) degrees
```

**Comment by dagewa** [comment]
Does integrated.pickle include improved centroids? Need that in place,
otherwise we'll just get the same result.

crystal_model, and the other dxtbx models, need slots in which to store
their errors. The ideal for the crystal would be to store the 9*9
covariance matrix for the state B. From that the errors in unit cell
quantities can be worked out wherever needed, and exotic quantities
depending on the covariance terms will not be lost.

**Comment by Anthchirp** [comment]
This is now available as a separate command, xia2.get_unit_cell_errors, and may or may not be moved into main xia2 at some point
