### ISSUE TITLE
Command of exclude_images="a:​b:c" in .xinfo via xia2/DIALS?

### ISSUE THREAD

**Issue by TH-Chang** [xia2/xia2#448]
Hi all,

I have met the issue that was happened a few times before. 

For example, I have 3600 images: images 1-2400 is good, images 2401-3000 is bad, and images 3001-3600 returns to good.

When I define images in xia2 .xinfo by START_END 1-2400 and START_END 3001-3600 in SWEEP1.
The program is failed for images 3001-3600 during the step of index or integrate. However, as using START_END 1-3600, the process is fine. But, it includes bad images (2401-3000) indeed.

Perhaps, the issue may cause by the indexing parameters or others used in images 1-2400 do not apply in images 3001-3600. 

Do it make sense to use the command " exclude_images="a:​b:c" in .xinfo? or I just use dials.scale to exclude these bad images?

Thank you.

**Comment by benjaminhwilliams** [comment]
Hi @TH-Chang, thanks for clarifying your issue.  May I ask whether the following command does what you need?
```
xia2 image=path/to/images/image_file_00001.cbf:1:2400 image=path/to/images/image_file_00001.cbf:3001:3600
```
using the correct path in place of `path/to/images` and filename in place of `image_file_00001.cbf`.

**Comment by rjgildea** [comment]
If you're finding that images 3001-3600 are not indexing when processed as an independant sweep, you could try adding the parameter `multi_sweep_indexing=True` in addition to those suggested by @benjaminhwilliams above, which should perform joint indexing on the two sub-sweeps simultaneously.

**Comment by benjaminhwilliams** [comment]
Ah, @rjgildea has beaten me to the follow-up comment.

You will see that the command I recommend above results in the two 'good' blocks of images being treated as separate sweeps, regardless of the fact that, from an experiment point of view, they are actually two separate wedges from the same sweep.  This is necessary in order to correctly integrate the data, as each reflection may span more than one image.  As such, we must avoid treating images 2400 and 3001 as adjacent.  The integrated reflection intensities from the two 'sweeps' (or wedges, if you prefer) will be scaled together at the end, to produce a single set of scaled reflections.

As @rjgildea suggests, you may find that, because your wedges are smaller than a full sweep, one or both may not contain enough reflections to get a good indexing solution.  In that case, you can aggregate the reflections from both wedges for the purposes of indexing, using the additional parameter `multi_sweep_indexing=True`.

To illustrate how this works, here are two schematic flow charts for comparison.
![Default narrow](https://user-images.githubusercontent.com/11389015/81592517-01b21380-93b6-11ea-88e3-d94368357624.png)
![Multi-sweep indexing narrow](https://user-images.githubusercontent.com/11389015/81593107-db40a800-93b6-11ea-90ff-2e87b08c09ed.png)

**Comment by TH-Chang** [comment]
Hi @rjgildea and @benjaminhwilliams 
Thank you both. YES, you are right. 

Specifically, when I treat two good blocks of images as separate independent sweeps for a single data-set collected from a crystal, it is usually failed for challenging causes. It seems that multi_sweep_indexing=True works well.

A follow-up question: 
What is a better or reasonable approach for dealing with the multiple data-sets (collected by different oscillation ranges e.g. 0-180, 45-225 ... from the same crystal) for the sulfur-SAD approach specifically? I usually use multiple sweeps in the xia2 interface. To make index more consistent between sweeps, does "multi_sweep_indexing=True" make sense to use in principle?

Thank you.

**Comment by benjaminhwilliams** [comment]
If you are confident that the same sample is illuminated for both sweeps, then `multi_sweep_indexing` should be useful for you.  In fact, the reason that the sweeps are refined separately is to allow for any small differences in the unit cell parameters between each sweep, such as might occur due to beam heating, radiation damage, different portions of the sample being illuminated, etc..  Of course, you'll need to use your judgement according to your apparatus, your sample and the details of your experiment, but I would imagine `multi_sweep_indexing` would usually be applicable in the case you describe.

**Comment by benjaminhwilliams** [comment]
@TH-Chang, I think we've answered your questions, so I'll close the issue.  Please feel free to reopen it if you have any further follow-up questions.
